Temporary audio manager + others
NotCorrin/Time-Crunch pull request #81
Opened 2022-10-02 17:16 UTC by PixiePA

- Fixed camera jitter
- Fixed error preventing auxiliary module use
- Fixed bug causing natural deceleration to work incorrectly
- Reduced deceleration from going above top speed
- Reduced airbrake turn rate. Brake turnrate now has minimum value.
- Doubled power of turbo hit
- Boosting after a turbo hit now removes passive deceleration for a short duration
- Implemented TurboHit event
- Temporary audio manager
- Fixed track alignment bugs

2022-10-03 01:56 UTC, NotCorrin commented
Not sure if we should push the temporary audio manager if we're handling audio with FMOD. Part of the FMOD setup is to remove audio listeners that work with the default Unity system with audio listeners that work with FMOD. Unsure if this will create problems in future...

2022-10-03 02:06 UTC, NotCorrin requested changes
Not sure if we should push the temporary audio manager if we're handling audio with FMOD. Part of the FMOD setup is to remove audio listeners that work with the default Unity system with audio listeners that work with FMOD. Unsure if this will create problems in future...

The reason why this branch was called temporary-audiomanager was just for submission purposes, it was never meant to be merged into the development branch.

2022-10-08 09:03 UTC, NotCorrin approved these changes

2022-10-08 11:03 UTC, HugoA-slash-UsernamePassword approved these changes

2022-10-08 11:25 UTC, merged